INSERT INTO users (username, profile_photo_url, bio, email) VALUES
('MickeyMouse', 'https://picsum.photos/100', 'Available || RVITM2024', 'user1@example.com'),
('DonaldDuck', 'https://picsum.photos/101', 'Dont stalk, lets talk', 'user2@example.com'),
('SpongeBob', 'https://picsum.photos/103', 'Life is a journey, It drives you crazy.', 'user3@example.com'),
('BugsBunny', 'https://picsum.photos/100', 'Wish me on 23 Dec', 'user4@example.com'),
('ScoobyDoo', '', 'Heart Stealer', 'user5@example.com'),
('TomCat', '', 'Dettol Stealer', 'user6@example.com'),
('HomerSimpson', '', 'Hotel Management', 'user7@example.com'),
('BartSimpson', '', 'Football Lover', 'user8@example.com'),
('FredFlintstone', '', 'Norwegian', 'user9@example.com'),
('GeorgeJetson', '', 'Living life my way', 'user10@example.com'),
('Sylvester', 'https://picsum.photos/100', 'Welcome To My Profile', 'user11@example.com'),
('Popeye', 'https://picsum.photos/101', 'Official Account', 'user12@example.com'),
('Shaggy', 'https://picsum.photos/102', 'Wish Me on 3 October', 'user13@example.com'),
('BartSimpson', 'https://picsum.photos/103', 'Aap Yaha Aaye Kisliye', 'user14@example.com'),
('SanskariLadka', 'https://picsum.photos/104', 'Sanskar Ladka', 'user15@example.com'),
('TheGrinch', 'https://picsum.photos/105', 'Aapne Bulaya Isiliye', 'user16@example.com'),
('Goku', 'https://picsum.photos/106', 'Gym Lover', 'user17@example.com'),
('Pikachu', 'https://picsum.photos/107', 'Aaye Hai Toh Kaam Bataiye', 'user18@example.com'),
('HomerSimpson', 'https://picsum.photos/108', 'Single', 'user19@example.com'),
('BartSimpson', 'https://picsum.photos/109', 'Has Toh Zara Aap Muskuraiye', 'user20@example.com'),
('BartSimpson', 'https://picsum.photos/110', 'Respect For All', 'user21@example.com'),
('SpongeBob', 'https://picsum.photos/111', 'InstaGram King', 'user22@example.com'),
('ScoobyDoo', 'https://picsum.photos/112', 'Cake Murder on 17 June', 'user23@example.com'),
('FredFlintstone', 'https://picsum.photos/113', 'Not Specified', 'user24@example.com'),
('MickeyMouse', 'https://picsum.photos/114', 'Photographer', 'user25@example.com'),
('ScoobyDoo', 'https://picsum.photos/115', 'Sdgfsdgsd', 'user26@example.com'),
('SpongeBob', 'https://picsum.photos/116', 'Music Addict', 'user27@example.com'),
('HomerSimpson', 'https://picsum.photos/117', 'Uhiusgfufiusf', 'user28@example.com'),
('MickeyMouse', 'https://picsum.photos/118', 'Singer', 'user29@example.com'),
('TomCat', 'https://picsum.photos/119', 'usdsgbcu', 'user30@example.com'),
('BartSimpson', 'https://picsum.photos/120', 'Proud To Be Hindu', 'user31@example.com'),
('HomerSimpson', 'https://picsum.photos/121', 'hucussgcusn', 'user32@example.com'),
('SpongeBob', 'https://picsum.photos/122', 'Big Fan Of Mahakal', 'user33@example.com'),
('ScoobyDoo', 'https://picsum.photos/123', 'Mr. Perfect', 'user34@example.com'),
('BartSimpson', 'https://picsum.photos/124', 'Hate Me or Date Me', 'user35@example.com'),
('MickeyMouse', 'https://picsum.photos/125', 'Photographer', 'user36@example.com'),
('ScoobyDoo', 'https://picsum.photos/126', 'gygyuuy', 'user37@example.com'),
('SpongeBob', 'https://picsum.photos/127', 'Foody', 'user38@example.com'),
('TomCat', 'https://picsum.photos/128', 'gfytfvy', 'user39@example.com'),
('FredFlintstone', 'https://picsum.photos/129', 'Single', 'user40@example.com'),
('GeorgeJetson', 'https://picsum.photos/130', 'fytfysguf', 'user41@example.com'),
('SpongeBob', 'https://picsum.photos/131', 'U will find a boy better than me but U don’t find a boy like me', 'user42@example.com'),
('BartSimpson', 'https://picsum.photos/132', 'Singer', 'user43@example.com'),
('MickeyMouse', 'https://picsum.photos/133', 'Music Addict', 'user44@example.com'),
('ScoobyDoo', 'https://picsum.photos/134', 'ytyftftyi', 'user45@example.com'),
('SpongeBob', 'https://picsum.photos/135', 'Sdgsfbg', 'user46@example.com'),
('BartSimpson', 'https://picsum.photos/136', 'ygyugdysgc', 'user47@example.com'),
('SanskariLadka', 'https://picsum.photos/137', 'Photographer', 'user48@example.com'),
('ScoobyDoo', 'https://picsum.photos/138', 'ygsgsogt', 'user49@example.com'),
('Goku', 'https://picsum.photos/139', 'Sanskar Ladka', 'user50@example.com');
